# Generated by Django 2.2.4 on 2019-11-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=11)),
                ('TelefoneFixo', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
